all:
g++ -dynamiclib -o BasicFileSystem.so BasicFileSystem.cpp
g++ createDisk.cpp -L/dir/ -lutils
g++ alocar.cpp -L/dir/ -lutils
g++ librar.cpp -L/dir/ -lutils
g++ stats.cpp -L/dir/ -lutils


./createDisk disk.co 20
./alocar disk.co
./Librar disk.co 4
